### ISSUE TITLE
Requires authentication, but when re-authenticated again it does nothing

### ISSUE THREAD

**Issue by AyraHikari** [hawkeye116477/playnite-legendary-plugin#49]
### Playnite version

10.32.0.18786

### Plugin version

1.5.0.40296

### Legendary Launcher version

0.20.34

### Bug description

It said 'Requires authentication', but when i click Authenticate and logged in with my Epic account, the browser is exit and nothing changed, no popup error or something.
Restart Playnite still got same error authentication

### Relevant log

```
30-01 12:38:30.562|DEBUG|LegendaryLibrary#LegendaryLibrary:Found 1 installed Epic games.
30-01 12:38:30.562|ERROR|LegendaryLibrary#LegendaryLibrary:Failed to import linked account Epic games details.
System.Exception: User is not authenticated.
   at LegendaryLibraryNS.Services.EpicAccountClient.<GetAssets>d__15.MoveNext() in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\Services\EpicAccountClient.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at LegendaryLibraryNS.LegendaryLibrary.<GetLibraryGames>d__17.MoveNext() in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\LegendaryLibrary.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryLibraryNS.LegendaryLibrary.GetGames(LibraryGetGamesArgs args) in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\LegendaryLibrary.cs:line 207
```

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/36266025/79971bc8-707d-4f47-9ebd-a09d3401f775)

**Comment by hawkeye116477** [comment]
Well, honestly I don't what to say you. There is no bug, it works fine for me. How are you sing in, using Epic or some other account like Sony, is 2 FA enabled?

**Comment by AyraHikari** [comment]
> Well, honestly I don't what to say you. It works fine for me. How are you sing in, using Epic or some other account like Sony, is 2FA enabled? Can you show something more from log, cuz I see here that it failed to import games, but no errors when you press button to authenticate?

Actually it works at first day, then after some weeks i got that error.
I'm using Epic account with Email for 2FA, disabling it still not work

**Comment by hawkeye116477** [comment]
> after some weeks i got that error.

Well, authentication isn't for forever. Token needs to be refreshed from time to time. If for some reason it's not possible to refresh, then you will need to authenticate again. In the past there was a problem with refreshing => https://github.com/hawkeye116477/playnite-legendary-plugin/issues/8, but that was fixed at 1.1.0 and another user confirmed that everyting is fine. So I assume that probably something wrong is on your side, maybe problems with Internet connection stability.

> no popup error or something

Sometimes error message can be seen at Playnite's ring.

**Comment by AyraHikari** [comment]
In my case, there's no user.json at .config/legendary
Tried logged in and it created user.json.lock with 0 bytes, then gone in a sec.
The issue still persist, but login with browser or Epic Launcher working fine

**Comment by hawkeye116477** [comment]
Well, you can try running at console `legendary auth --delete`. Check also if Heroic or another Legendary instance isn't runned, that may cause problems.

**Comment by AyraHikari** [comment]
Delete user auth data didn't make it work.
Also when i logged in with `legendary auth` cli, i got an error after auth.
Perhaps it's actually legendary error side? or this is normal?
```
[cli] INFO: Testing existing login data if present...
[WebViewHelper] INFO: Opening Epic Games login window...
[0131/133512.484:ERROR:check.cc(314)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[0131/133525.934:ERROR:check.cc(314)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[0131/133531.049:ERROR:check.cc(314)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[0131/133538.375:ERROR:check.cc(314)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[Core] ERROR: Logging in failed with JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), please try again.
[WebViewHelper] INFO: Closing login window...
[cli] ERROR: WebView login attempt failed, please see log for details.
```

**Comment by hawkeye116477** [comment]
No, it's not normal. I see similar thing reported at https://github.com/derrod/legendary/issues/586. In that case I can't help, you'll need to write about this at Legendary's GitHub or Discord.
